namespace: production
resources:
  - service.yaml
  - deployment.yaml
images:
  - name: docker.io/argoprojregistry/argo-workflows-demo-app
    newName: docker.io/argoprojregistry/argo-workflows-demo-app
    newTag: canary
