namespace: production
resources:
  - ../../base
patchesStrategicMerge:
  - patch-deployment.yaml
  - patch-service.yaml
images:
  - name: docker.io/argoprojregistry/argo-workflows-demo-app
    newName: docker.io/argoprojregistry/argo-workflows-demo-app
    newTag: canary
